name: Liquibase Migration Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v4

      - name: ✅ Install Liquibase & MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client unzip
          curl -L https://github.com/liquibase/liquibase/releases/download/v4.33.0/liquibase-4.33.0.zip -o liquibase.zip
          unzip liquibase.zip
          sudo ln -s $(pwd)/liquibase/liquibase /usr/local/bin/liquibase

      - name: ✅ Validate Changesets
        run: liquibase --changeLogFile=changelogs/master-changelog.xml validate

      - name: ✅ Show Pending Changes (DEV)
        run: liquibase --url="${{ secrets.DEV_DB_URL }}" --changeLogFile=changelogs/master-changelog.xml status

      - name: ✅ Deploy to DEV
        run: liquibase --url="${{ secrets.DEV_DB_URL }}" --changeLogFile=changelogs/master-changelog.xml update

      - name: ✅ Smoke Test
        run: mysql -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASS }} -h ${{ secrets.DB_HOST }} -e "SELECT 1"

  promote-to-qa:
    needs: deploy
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4

      - name: ✅ Deploy to QA
        run: liquibase --url="${{ secrets.QA_DB_URL }}" --changeLogFile=changelogs/master-changelog.xml update

  promote-to-prod:
    needs: promote-to-qa
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4

      - name: ✅ Deploy to PROD
        run: liquibase --url="${{ secrets.PROD_DB_URL }}" --changeLogFile=changelogs/master-changelog.xml update
